config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: %i[new create show]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true }, inclusion: { in: (0..5) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @reviews = @restaurant.reviews
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(params_restaurant)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
   @restaurant.update(params_restaurant)
   redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path(@restaurant)
  end

  private

  def params_restaurant
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(params_review)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def show
    @review = Review.find(params[:id])
    @review = review.new
  end

  private
  def params_review
    params.require(:review).permit(:content, :rating)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category, collection: ["chinese", "italian", "japanese", "french", "belgian"] %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/restaurants/edit.html.erb
<h1 class="m-3">Edit <%= @restaurant.name %> </h1>
<%= render 'form', restaurant: @restaurant %>
<span class="m-2"><%= link_to  "Delete restaurant", restaurant_path(@restaurant), method: :delete, data: { confirm: 'Are you sure?' } %></span>
<span class="m-2"> <%= link_to  "Go back", restaurant_path(@restaurant) %></span>
<span class="m-2"> <%= link_to  "Go to list", restaurants_path %></span>

app/views/restaurants/index.html.erb
<h1 class="m-3">All restaurants</h1>
<ul>
<% @restaurants.each do |restaurant| %>
<li><%= link_to(restaurant.name, restaurant_path(restaurant)) %></li>
<% end %>
</ul>

app/views/restaurants/new.html.erb
<h1> Create a restaurant </h1>
<%= render 'form', restaurant: @restaurant %>

<%= link_to  "Back to list", restaurants_path %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %> </h1>
<p>Category: <%= @restaurant.category %></p>
<p>Adress: <%= @restaurant.address %></p>
<p>Phone number: <%= @restaurant.phone_number %></p>

<span class="m-2"><%= link_to "Edit restaurant", edit_restaurant_path(@restaurant) %></span>
<span class="m-2"><%= link_to  "Delete restaurant", restaurant_path(@restaurant), method: :delete, data: { confirm: 'Are you sure?' } %></span>
<span class="m-2"><%= link_to  "Back to list", restaurants_path %></span>

<h3 class="mt-4">Reviews</h3>
<ul>
  <% @reviews.each do |review| %>
    <li>
      <%= review.content %>
      <%= review.rating %>
    </li>
  <% end %>
</ul>


<p>
  <%= link_to 'Add Review', new_restaurant_review_path(@restaurant), class: 'btn btn-success' %>
</p>

app/views/reviews/new.html.erb
<h1>Add a new review for <%= @restaurant.name %></h1>


<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, collection: [1, 2, 3, 4, 5] %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>